[project]
name = "ygg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hy>=1.0.0",
    "hyrule>=0.8.0",
    "toolz>=1.0.0",
]
